"""initial schema

Revision ID: 3174a00b6f6a
Revises: 
Create Date: 2026-08-13 10:10:01.625980
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3174a00b6f6a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
